add_self_loop: false
agg: mean
batch_size: 128
best_model_path: checkpoints/val_0.2/LA-SAGE-S/amazon/2023-07-05_21-04-21/best_val_model_1234.pth
dataset: amazon
dataset_seed: 717
dropout: 0.6
epochs: 100
eval_interval: 1
flush_seconds: 60
force_reload: false
full_neighbors: true
gpu_id: 4
hid_dim: 256
homo: true
hyper_file: config/
lr: 0.01
lr_scheduler: false
mlp_activation: elu
model: LA-SAGE-S
model_name: LA-SAGE-S
monitor: auc_gnn
multirun: 10
n_layer: 1
no_dev: false
norm_feat: true
num_trans: 1
num_workers: 8
optimizer: Adam
patience: 20
proj: true
reduction: mean
relation_agg: cat
resi: 0.2
run_best: false
sampled_neighbors:
- -1
- -1
- -1
sampling_type: in
seed: 1234
test_batch_size: 4096
test_each_epoch: false
thres: 0.5
threshold_moving: true
train_size: 0.4
val_size: 0.2
weight_decay: 0.0
weighted_loss: false
